### ISSUE TITLE
"Module did not self-register" using workerpool

### ISSUE THREAD

**Issue by ericman314** [fuzhenn/node-svg2img#33]
I'm running into a bug while using `svg2img` inside of worker threads using [workerpool.](https://github.com/josdejong/workerpool) If I convert one image at a time using workerpool, everything works fine. But if I try to convert two or more in parallel, I am getting this error:  

```
Error: Module did not self-register.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1003:18)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/eric/Documents/svg2img-workerpool/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
```

Here's an example demonstrating the issue: https://github.com/ericman314/svg2img-workerpool

I have no idea if this is a bug with workerpool, svg2img, or one of their dependencies. The puzzling thing is that it works when a single child thread runs, but not when multiple child threads are running.

**Comment by ericman314** [comment]
Ah nevermind, looks like workers are not supported by `node-canvas`: https://github.com/Automattic/node-canvas/issues/1394
